---
- hosts: all
  roles:
    - common

- hosts: storage
  roles:
    - postgres
    - ansible-role-nfs

- hosts: docker
  roles:
    - docker

- hosts: local
  roles:
    - local
    - emulationstation
