---
- name: drop beats deb packages
  copy:
    src: beats/
    dest: /opt/beats/
  tags: beats

- include: file.yml
  tags: beats

- include: packet.yml
  tags: beats

- include: top.yml
  tags: beats
