---
- name: install dependencies
  tags: emulationstation
  apt: name={{item}} update_cache=true state=present
  with_items:
    - libsdl2-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-date-time-dev
    - libboost-locale-dev
    - libboost1.55-all-dev
    - libfreeimage-dev
    - libfreetype6-dev
    - libeigen3-dev
    - libcurl4-openssl-dev
    - libasound2-dev
    - build-essential
    - cmake

- name: clone emulationstation git repo
  tags: emulationstation
  git:
    repo: https://github.com/Aloshi/EmulationStation.git
    dest: "{{ emulationstation_install_dir }}"
  register: gitclone

- name: cmake emulationstation dir
  tags: emulationstation
  command: cmake . chdir={{ emulationstation_install_dir }}
  when: gitclone.changed

- name: make emulationstation dir
  tags: emulationstation
  command: make chdir={{ emulationstation_install_dir }}
  when: gitclone.changed

- name: make install emulationstation
  tags: emulationstation
  command: make install chdir={{ emulationstation_install_dir }}
  when: gitclone.changed

- name: create emulationstation config dir
  tags: emulationstation
  file:
    path: "{{ emulationstation_config_dir }}"
    owner: frisbee
    group: frisbee
    state: directory

- name: move config files
  tags: emulationstation
  copy:
    src: es_config/
    dest: "{{ emulationstation_config_dir }}"
    owner: frisbee
    group: frisbee
