---
# This Playbook runs all the common plays in the deployment
- name: remove pi user
  user:
    name: pi
    state: absent
    remove: yes

- name: update dist packages
  apt:
    update_cache: true
    upgrade: full

- name: install some basic packages
  apt: name={{item}} update_cache=true state=latest
  with_items:
    - apt-transport-https
    - bash
    - openssl
    - libssl-dev
    - vim
    - git
    - python-dev
    - build-essential
    - tmux
    - screen
  tags: packages
