---
# This Playbook runs all the common plays in the deployment
- name: remove pi user
  user:
    name: pi
    state: absent
    remove: yes

- name: stop kibana on craptop
  service:
    name: kibana
    state: stopped
  when: "'craptop' in group_names"
  tags: blah

- name: update dist packages
  apt:
    update_cache: true
    upgrade: full
  tags: blah

- name: install some basic packages
  apt: name={{item}} update_cache=true state=latest
  with_items:
    - apt-transport-https
    - bash
    - openssl
    - libssl-dev
    - vim
    - git
    - python-dev
    - build-essential
    - tmux
    - screen
  tags: blah

- name: turn kibana back on for craptop
  service:
    name: kibana
    state: started
  when: "'craptop' in group_names"
  tags: blah
