---
# This playbook starts some containers
- name: remove pirate user
  user:
    name: pirate
    state: absent
    remove: yes

- name: stop containers first
  tags: docker
  docker:
    image: hypriot/rpi-python
    state: stopped

- name: start consul
  tags: docker
  docker:
    name: py mover
    image: hypriot/rpi-python

#ansible docker -a "sudo docker exec consul consul join picl-docker-0*"
