---
# This playbook sets up postgresql on pidrive
# iptables -A INPUT -p tcp --dport 22 -j ACCEPT
- name: install postgresql
  tags: storage
  apt: name={{ item }} state=present
  with_items:
    - postgresql-client-9.4
    - postgresql-9.4
    - postgresql-contrib-9.4
    - libpq-dev
    - python-psycopg2

- name: open postgres listen address
  tags: storage
  lineinfile:
    dest: /etc/postgresql/9.4/main/postgresql.conf
    regexp: "#listen_addresses ="
    line: "listen_addresses = '*'"

- name: open up postgres accepted connections
  tags: storage
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    owner: postgres
    group: postgres

- name: restart postgres
  tags: storage
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: create user
  tags: storage
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER
    state: present

- name: create database
  tags: storage
  postgresql_db:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: present

- name: ensure user has access to database
  tags: storage
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"

- name: set up media server database
  tags: storage
  include: roles/postgres/tasks/media.yml
